### ISSUE TITLE
轻量但不简洁，使用下来还不如我自己处理每个页面但逻辑

### ISSUE THREAD

**Issue by oOJohn6Oo** [panyiho/EasyPermission#1]
掘金：参考google samples，个人认为最友好的申请权限流程应该是

1. 用户点击功能按钮（如扫一扫），直接申请需要权限（摄像头权限），调用系统弹框进行与用户交互。
2. 用户拒绝，那么弹框提示用户我们需要权限的理由，用户点击同意，再次调用系统弹框申请权限。
3. 用户再次拒绝（已经点击了不再提醒），提示用户使用该功能必须获取权限，引导用户去设置界面手动开启。

我尝试用此框架处理情况2很繁琐，虽然这是Google的锅，总喜欢把简单的问题复杂化。

另外发现代码中用的是Activity获取fragmentManager，但代码已经过时，是否考虑改成FragmentActivity或者AppCompatActivity。

**Comment by panyiho** [comment]
你说的这种逻辑，其实我们框架都支持，不太明白你说的繁琐的点在哪里，因为各种回调都有，比你直接调用Activity的权限api方便多了，至于说为啥不切换到AppCompatActivty是因为，不想依赖太多的东西，保持兼容性和copy即用的原则，你可以直接copy代码过去，按需自行修改就可以
